<a href="https://colab.research.google.com/github/Rudransh840/ML--Lab/blob/main/ML_Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/Iris.csv')

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [5]:
subset=df.loc[:,["SepalLengthCm","SepalWidthCm"]]

In [6]:
print(subset.head())

   SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6

In [7]:
subset1=df.iloc[:,[2,3,-1]]

In [8]:
subset1.head()

   SepalWidthCm  PetalLengthCm      Species
0           3.5            1.4  Iris-setosa
1           3.0            1.4  Iris-setosa
2           3.2            1.3  Iris-setosa
3           3.1            1.5  Iris-setosa
4           3.6            1.4  Iris-setosa

In [9]:
subset1=df.iloc[:,[2,4]]

In [10]:
subset1.head()

   SepalWidthCm  PetalWidthCm
0           3.5           0.2
1           3.0           0.2
2           3.2           0.2
3           3.1           0.2
4           3.6           0.2

In [11]:
list1=list(range(6))

In [12]:
subset2=df.iloc[:,list1]

In [13]:
subset2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
df.loc[20,'SepalWidthCm']

np.float64(3.4)

In [15]:
df.iloc[20,2]

np.float64(3.4)

In [16]:
df.iloc[[0,99,149],[0,3,5]]

      Id  PetalLengthCm          Species
0      1            1.4      Iris-setosa
99   100            4.1  Iris-versicolor
149  150            5.1   Iris-virginica

In [17]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [18]:
df.notnull().sum()

Id               150
SepalLengthCm    150
SepalWidthCm     150
PetalLengthCm    150
PetalWidthCm     150
Species          150
dtype: int64

In [19]:
df.loc[10:15,"SepalLengthCm"]=np.nan

In [20]:
df.isnull().sum()

Id               0
SepalLengthCm    6
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [21]:
df.loc[20:25,"SepalWidthCm"]=np.nan

In [22]:
df.isnull().sum()

Id               0
SepalLengthCm    6
SepalWidthCm     6
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [23]:
df["SepalLengthCm"].fillna(df["SepalLengthCm"].mean(),inplace=True)

/tmp/ipykernel_6869/4267940951.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["SepalLengthCm"].fillna(df["SepalLengthCm"].mean(),inplace=True)

In [24]:
df["PetalWidthCm"].fillna(df["PetalWidthCm"].median(),inplace=True)

/tmp/ipykernel_6869/3656538085.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["PetalWidthCm"].fillna(df["PetalWidthCm"].median(),inplace=True)

In [25]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     6
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [26]:
df.dropna(inplace=True)

In [27]:
df.rename(columns={'SepalLengthCm':'SepalLength'},inplace=True)

In [28]:
df['SepalLength']=df['SepalLength'].astype(float)

In [29]:
df['PetalWidthCm']=df['SepalWidthCm'].astype(float)

In [30]:
df.iloc[:,-1]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 144, dtype: object